adobe_analytics.settings:
  type: config_object
  label: 'Adobe Analytics settings'
  mapping:
    role_tracking_type:
      type: string
      label: 'Role Tracking Type'
    js_file_location:
      type: string
      label: 'Javascript file location'
    codesnippet:
      type: string
      label: 'Codesnippet'
    version:
      type: string
      label: 'Version'
    image_file_location:
      type: string
      label: 'Image file location'
    token_cache_lifetime:
      type: integer
      label: 'Token cache lifetime'
    extra_variables:
      type: sequence
      label: 'Extra variables'
      sequence:
        type: string
        label: 'The extra variables'
    track_roles:
      type: sequence
      label: 'Track roles'
      sequence:
        type: string
        label: 'Roles to track or not track'
